---
Parameters:
  amiId:
    Description: Enter the ami id of the ec2 instance to be created
    Type: String
    Default: ami-087c17d1fe0178315
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: !Ref amiId
      InstanceType: t2.micro
