---
Parameters:
  MyKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: KeyPair Name

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0c2b8ca1dad447f8a
      InstanceType: t2.micro
      KeyName: !Ref MyKeyPair
      SecurityGroups:
        - !Ref SecurityGroup
      Tags:
        - Key: Name
          Value: Webserver1        
      UserData: 
        Fn::Base64: |
          #!/bin/bash -xe
          yum update -y
          yum install -y httpd
          systemctl start httpd
          systemctl enable httpd
          echo "<h1>Hello World !!</h1>" >> /var/www/html/index.html
          echo "<br/>" >> /var/www/html/index.html
          echo "<p>Availability Zone : $(curl http://169.254.169.254/latest/meta-data/placement/availability-zone)</p>" >> /var/www/html/index.html
          echo "<p>Instance Id       : $(curl http://169.254.169.254/latest/meta-data/instance-id)</p>" >> /var/www/html/index.html
          echo "<p>Public Ip         : $(curl http://169.254.169.254/latest/meta-data/public-ipv4)</p>" >> /var/www/html/index.html
          echo "<p>Private Ip        : $(curl http://169.254.169.254/latest/meta-data/local-ipv4)</p>" >> /var/www/html/index.html

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and HTTP
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      - CidrIp: 0.0.0.0/0
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80
        
Outputs:
  PublicIp:
    Description: PublicIP address
    Value: !GetAtt MyInstance.PublicIp